version: "3.7"

services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    # container_name: fastapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.fastapi.entrypoints=web"
      - "traefik.http.services.fastapi.loadbalancer.server.port=1234"
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    environment:
      - ENV_FILE=${ENV_FILE}
    networks:
      - traefik

  mongodb:
    image: mongo:latest
    # container_name: mongodb
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null", "--logappend"]
    networks:
      - traefik

volumes:
  mongo-data:

networks:
  traefik:
    external: true